### PR TITLE
#78 Fix plugin fails error

### LINKED ISSUE #78: Getting plugin not found error
# Details

```
t=2022-03-08T23:52:22+1300 lvl=eror msg="Could not start plugin" logger=plugin.manager pluginId=msupplyfoundation-datasource err="Unrecognized remote plugin message: 2022/03/08 23:52:22 notifying bugsnag: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub\n\nThis usually means that the plugin is either invalid or simply needs to be recompiled to support the latest protocol."
```

In mac grafana tries to use the ARM version of the executable which also breaks saying could not find file.

I did recompiled the app in my m1 mac system but it was broken before I tinkered. I forgot to take the error log entry though.

Definitely getting this error because Grafana for some reasons cannot run the backend executable.

### PR DESCRIPTION
**Pull request by sworup**
Fixes #78

### CODE REVIEW

**Comment by sworup** [comment]
The draft code until now fixes the case where users could not be queried when `CreateReports` calls user.go's `GetEmails` method.

However, a bug still persists.

There are two `CreateReports` methods, one that takes params and others that do not. The one that does not take params is called at the very start when the plugin is loaded. It takes params from config and queries in the users that way. The problem is `GetEmails` fails in this condition. This call happens where there are pre-existing schedulers and the system tries to run them when the plugin loads.

If there are no pre-existing schedulers then the attempt to run `GetEmails` never takes place and the plugin loads, it also runs on the normal flow so no errors there when the code is run later. 

if there are pre-existing schedulers when `GetEmails` fails and the error stops the plugin from loading hence cause plugin cannot be loaded error. This is the main error of this issue and I am working on fixing this.

**Comment by sworup** [comment]
@Mai21 I have uploaded the fixed plugin in demo-dash. it still has problems if you do not set it up correctly but at least it works now.

**Comment by ujwalSussol** [comment]
2022-04-01-T10-55  : Thanks @sworup  : I am aiming to understand this fix today...

**Comment by ujwalSussol** [comment]
2022-04-01-T14-32  : thanks to @sworup  and @anildahalsussol  for explaining how complicated the setup is.  For now @sworup  has updated the plugin on :   demo-board.msupply.org  ...  so will aim to grab this and introduce it to the Sames server... if possible.

**Review by mark-prins — APPROVED** [review]
🎉  awesome!! nice work @sworup - thanks

**Comment by sworup** [comment]
@mark-prins @ujwalSussol 
In current situation, I have made the plugin work if you follow the normal flow. It has bugs and some lack of error handling, which should be our next concen. 
For instance, most of the bugs, when happens, breaks without much warning. This is specially a problem for users who cannot check the logs, and the logs even are sometimes not very helpful since the bug was not handled and log record would have partial error details.
Another problem is when user disables the plugin and trys to enable it again. The plugin runs an init function that reschedules all of the schedulers, if that breaks either plugin would not load at all, or it would load, the schedules are never added to the chron job and there is no visual feedback. There is no button to get the schedules to start manually either so we would have to disable and enable the plugin again. The main concern is user would not know that pre-existing shedule are actaually not running right now.

I am working on a plugin-rewirite for this plugin in which Iam trying to handle the above concerns along with bringing in code changes with version 8 upgrade. There are some other things too. 

Until that is done, I am going to merge this PR, this is not perfect but the plugin would work for now.

**Comment by ujwalSussol** [comment]
> @mark-prins @ujwalSussol In current situation, I have made the plugin work if you follow the normal flow. It has bugs and some lack of error handling, which should be our next concen. For instance, most of the bugs, when happens, breaks without much warning. This is specially a problem for users who cannot check the logs, and the logs even are sometimes not very helpful since the bug was not handled and log record would have partial error details. Another problem is when user disables the plugin and trys to enable it again. The plugin runs an init function that reschedules all of the schedulers, if that breaks either plugin would not load at all, or it would load, the schedules are never added to the chron job and there is no visual feedback. There is no button to get the schedules to start manually either so we would have to disable and enable the plugin again. The main concern is user would not know that pre-existing shedule are actaually not running right now.
> 
> I am working on a plugin-rewirite for this plugin in which Iam trying to handle the above concerns along with bringing in code changes with version 8 upgrade. There are some other things too.
> 
> Until that is done, I am going to merge this PR, this is not perfect but the plugin would work for now.

@sworup  :  I am happy with the plan...  So this PR needs Grafana v8 --  This we need to be clear for future support.  @Mai21 Are you happy with this plan.

**Pull request merged**
