### PR TITLE
#81 Grafana 8 rewrite

### PR DESCRIPTION
**Pull request by sworup**
Things done in this PR

- A rewrite to make the plugin as compatible as possible to Grafana v8, this might mean this version would not work with Grafana v7. 
- Changes include different way to call sdk and structure files. The setup code has also been completely reshaped to be more compatible with Grafana v8.
- Combined backend (datasource) and frontend (app) plugins into a single Grafana app plugin. 
- We no longer use GCC tied SQLite package. It has been replaced.
- Removed need to show plugin's SQLite datasource in Grafana UI. Original code was never panning to use the SQLite datasource separately, it was just a limitation while creating plugin. Now the plugin datasource has no interface so it is enabled by default with the plugin and cannot be used outside of it. It won't show in the datasource list or anywhere in Grafana UI.
- Updated the ui with these major changes
  - Forms have major ui and component related changes
  - UI will no longer change with form changes. This dynamic data update on field changes was causing cases were incomplete schedules and report groups were being created unintentionally, causing the emailer to bug out.
  - UI forms will now collect data and save it when save button is clicked as a chunk.
  - The Report group and scheduler has extra UI details that would make things bit more clearer.
- Added validations that would stop wrongly composed data from saving.
- Removed panic calls in the plugin overall. Panic is supposed to return a output but Grafana was tying to look for grpc errors that was never there causing the resource not found error to override all errors. This meant every error, no matter what caused it, would show this resource not found error causing debugging to be a royal pain.
- Updated/added error handling measures that would show more descriptive errors in log and to users. Log will have more detailed errors while user will see more human readable error (not implying that developers and inhuman 😄 ).
- Updated the Golang resources to match this single resource to save entire report-group or schedule related data as a chunk, setup. Previously schedule would be created seperately and panels would be added and removed from it with seperate resource. Now the updates would happen together making validation more robust.
- 🐛  Fixed some of the bugs that have been there from the start.

### CODE REVIEW

**Comment by Mai21** [comment]
@sworup 
I am testing this today.
Here are the issues I found so far.
1. Schedules > New (Also Edit) > Interval dropdown list is empty
Screen Shot 2022-05-12 at 4 19 32 PM

2. Unnecessary ! mark is under "Selected panel" section (Maybe ! mark beside "Available Panels" from the old version)
Screen Shot 2022-05-12 at 4 40 28 PM

3.  ! mark does not work in each panel. Also label "VARIABLES" is missing.
4. Lookback period label is not shown, DDL is empty
Screen Shot 2022-05-12 at 4 40 37 PM

5. Lookback period is shown even when it is hidden in the dashboard 

6. When one panel is selected, other panels are selected at the same time...

https://user-images.githubusercontent.com/36495540/167996511-fc41f740-5a74-4369-8b11-8074ad7369dc.mov

**Comment by sworup** [comment]
Thanks @Mai21. This will be really helpful. Working on the bug fixes right away.

**Comment by sworup** [comment]
> 1. Schedules > New (Also Edit) > Interval dropdown list is empty

@Mai21 I just tested this in demo-dash and I do not see this issue there.

Screen Shot 2022-05-12 at 11 28 50 AM

**Comment by Mai21** [comment]
@sworup Are you using Windows? I found out that the issues from 1 - 5 are only seen in Mac. I cleared the cache, also opened it from the other mac but all the same as I reported. But I opened it in the demo server and other windows 11, then it works well. The browser is Chrome in both windows and mac.

**Comment by Mai21** [comment]
@sworup I tested with another Mac OS and it works. But clearing the cache in my Mac does not solve the issues... so weird...
Anyway, keep testing on windows.

One thing I'd like you to add is the function of "SEND TEST". It used to be in the schedules and it is really helpful to test when we create a new schedule.


Screen Shot 2022-05-17 at 6 04 24 PM

**Comment by mark-prins** [comment]
Wow! 😮 

that's awesome - impressive work @sworup, a very comprehensive rewrite.
I put in some wording suggestions for the .md files in e8415f2. mostly nit-picky, just thought to add them in 🤷 

I was also testing on a mac, so this might not be an issue for you? Deleting a group or schedule gives me this:
Screen Shot 2022-05-19 at 12 34 59 PM

And I had an existing schedule which blows the UI out 😁 
Screen Shot 2022-05-19 at 12 36 51 PM

Was wondering if the msupply-table plugin works with the changes? Having trouble running that locally.. so thought I'd just ask.

**Comment by Mai21** [comment]
@mark-prins I checked if msupply-table plugin works, and it did well:)
It was fixed in this [commit](https://github.com/openmsupply/msupply-dashboard-app/pull/82/commits/194ebc301db521c4d2125f61ad84592962c54841)

**Comment by mark-prins** [comment]
good to hear! thanks @Mai21 

( I noticed when looking at the commit that we have a typo in the name of the error handling file `/pkg/server/erros.go` 🤣 )

**Comment by sworup** [comment]
> @sworup I tested with another Mac OS and it works. But clearing the cache in my Mac does not solve the issues... so weird... Anyway, keep testing on windows.
> 
> One thing I'd like you to add is the function of "SEND TEST". It used to be in the schedules and it is really helpful to test when we create a new schedule.
> 
> [Screen Shot 2022-05-17 at 6 04 24 PM](https://user-images.githubusercontent.com/36495540/168740290-2468b1a6-27f7-409c-ba84-9f7195496bc8.png)

Added with f6c36e9

**Comment by Mai21** [comment]
Test plan 
* Installation
- [ ] Upgrade from v7 to v8 (The plugin was already installed)
  - [ ] The old setting is available
- [ ] Newly install in v8 
  - [ ] No error for configuration 
- [ ] Config page : everything can be changed, validation works properly

* Scheduler
    - [ ] (Upgrade) the old setting for groups, schedules is available 
    - [ ] Report Groups  
      - [ ] Add a new group 
      - [ ] Edit the group 
      - [ ] Delete the group  
    - [ ] Schedules  
      - [ ] Add a new schedule 
      - [ ] Edit the schedule 
      - [ ] Delete the schedule
      - [ ] Variables : Lookback period
      - [ ] Variables : filters
      - [X] Send test
      - [ ] Sending email by the scheduler  (Daily, Weekly, Fortnightly, Monthly...)

**Comment by Mai21** [comment]
@sworup I found one bug about the label in the schedules list.
The name of panel shown in the list (`Current Stock - Test mSupply table`) and the actual panel saved(`Simple dashboard with the time filter`) are different.
- The name in the list
Screen Shot 2022-06-02 at 12 05 21 PM

- The actual panel saved
Screen Shot 2022-06-02 at 12 05 42 PM
Screen Shot 2022-06-02 at 12 06 05 PM

**Comment by Mai21** [comment]
@sworup Apart from the bug about the label, here are the bugs I found. 
1. Lookback period seems not working... 
2. Even though the time range is not used in the query, if there is at least one variable in the query, lookback is in the config on the schedule edit page (but when the lookback is empty, still works).
3. Edit schedule: sometimes variables are missing even though these were saved once

**Comment by sworup** [comment]
> @sworup I found one bug about the label in the schedules list. The name of panel shown in the list (`Current Stock - Test mSupply table`) and the actual panel saved(`Simple dashboard with the time filter`) are different.
> 
> * The name in the list
>   [Screen Shot 2022-06-02 at 12 05 21 PM](https://user-images.githubusercontent.com/36495540/171521626-cabbb50f-c264-469c-994e-949ab1bf16e5.png)
> * The actual panel saved
>   [Screen Shot 2022-06-02 at 12 05 42 PM](https://user-images.githubusercontent.com/36495540/171521659-f011238f-8494-4d6d-8142-cf94a7de83cb.png)
>   [Screen Shot 2022-06-02 at 12 06 05 PM](https://user-images.githubusercontent.com/36495540/171521666-c8ac180c-0e4a-4037-a58b-f9771f4f7f35.png)

@Mai21 resolved with 56b8f1a

**Comment by sworup** [comment]
> @sworup Apart from the bug about the label, here are the bugs I found.
> 
> 1. Lookback period seems not working...
> 2. Even though the time range is not used in the query, if there is at least one variable in the query, lookback is in the config on the schedule edit page (but when the lookback is empty, still works).

@Mai21 I had set lookback to always show during testing and forgotten to put it back. Resolved with 660f8c8

> 3. Edit schedule: sometimes variables are missing even though these were saved once

**Comment by Mai21** [comment]
Hi @sworup  I newly installed this plugin and am testing in the DEMO2 server, it looks really nice!
One thing about that the look back is not working, this is from the original bug I mentioned in the issue #76 

The interval is used as the lookback... so please have a look and fix it in reportEmailer.go ? 
Thanks a lot!

**Pull request merged**
