### PR TITLE
#39 Right align numbers

### PR DESCRIPTION
**Pull request by joshxg**
This will make numbers written as numbers (also maybe im missing some other data type which will be written with a number format?)

image

But: This is removing the style of the cell and making it different from the row. PRing this as is because I'm unsure of a solution and looking for ideas.

You can get a ref to the style of the row (or specifically a cell in the row), but you can't get the actual attributes of the style in order to be able to create a new style with the `number_format` appended to it, so this just overwrites the whole style. Hm.

Also, there is also the header. Hmx2

### CODE REVIEW

**Comment by joshxg** [comment]
Also tried using `SetRowValues` (which should be used anyway), and that didn't help - (currently taking the first cell of all the rows and duplicating that style into every cell written)

**Review by wlthomson — APPROVED** [review]
Approving for now to avoid blocking, but will have a try to see if I can make any progress on this.

**Review by mark-prins — APPROVED** [review]
works a treat. 
The formatting bothered me, but I can't find a way around that. So let's just go for it!

**Comment by mark-prins** [comment]
Actually, setting the default font on the template works fine 😉

**Pull request merged**
